DROP DATABASE IF EXISTS DCDB;
CREATE DATABASE DCDB;
USE DCDB;

CREATE TABLE PLAYERS (
	ID INT NOT NULL AUTO_INCREMENT,
	NICKNAME VARCHAR (10),
	EMAIL VARCHAR (25),
	PASSWORD VARCHAR (16),
	PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE GAME(
	ID INT NOT NULL AUTO_INCREMENT,
	ENDDATE VARCHAR(100),
	PRIMARY KEY (ID)
)ENGINE=InnoDB;

CREATE TABLE RECORD(
	ID INT NOT NULL AUTO_INCREMENT,
	GAME_ID INT,
	PLAYER1 INT,
	FOREIGN KEY (PLAYER1) REFERENCES PLAYERS(ID),
	FOREIGN KEY (GAME_ID) REFERENCES GAME(ID),
	PRIMARY KEY (ID)
)ENGINE=InnoDB;

INSERT INTO PLAYERS VALUES(NULL, 'ANA', 'ANA@123','cvn');
INSERT INTO PLAYERS VALUES(NULL, 'PEDRO', 'PEDRO@123','htyy');
INSERT INTO PLAYERS VALUES(NULL, 'Jan', 'JAN@123','anasdana');
INSERT INTO PLAYERS VALUES(NULL, 'Elia', 'Elia@123','213j');
INSERT INTO PLAYERS VALUES(NULL, 'ZAPATO', 'ZAPA@123','123d');

INSERT INTO GAME VALUES(NULL,'23abril11pm 10ANA');
INSERT INTO GAME VALUES(NULL,'24abril1pm,50,Pedro');


INSERT INTO RECORD VALUES (NULL,1,1);
INSERT INTO RECORD VALUES (NULL,1,2);
INSERT INTO RECORD VALUES (NULL,1,3);
INSERT INTO RECORD VALUES (NULL,1,4);
INSERT INTO RECORD VALUES (NULL,1,5);



